In [101]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

import string
import numpy as np
import nltk



from nltk.stem.porter import PorterStemmer

In [107]:
df = pd.read_csv("train.tsv",sep='\t' , encoding='utf-8', nrows = 10)
df_test =  pd.read_csv("test.tsv",sep='\t' , encoding='utf-8' )
df.drop(["PhraseId","SentenceId"],axis=1,inplace=True) # remove useless columns
df_test.drop(["PhraseId","SentenceId"],axis=1,inplace=True) # remove useless columns
df.head()
df.shape

(10, 2)

In [108]:
df.head()

                                              Phrase  Sentiment
0  A series of escapades demonstrating the adage ...          1
1  A series of escapades demonstrating the adage ...          2
2                                           A series          2
3                                                  A          2
4                                             series          2

In [109]:
# remove punctionation
stemmer = PorterStemmer()
def remove_punctuation(s):
    s = ''.join([i for i in s if i not in set(string.punctuation)])
    return s

df['Phrase'] = df['Phrase'].apply(remove_punctuation)

def stem_tokens(tokens, stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stems = stem_tokens(tokens, stemmer)
    return stems

In [110]:
vect = TfidfVectorizer(sublinear_tf=True, max_df=0.5, analyzer='word', stop_words='english' , tokenizer=tokenize , ngram_range=(1, 2), strip_accents = 'ascii')

In [111]:
X = vect.fit_transform(df.pop('Phrase'))

r = df[['Sentiment']].copy()

del df

df = pd.DataFrame(X.toarray(), columns=vect.get_feature_names())

del X
del vect

In [112]:
df.head()

,adag,adag good,amus,amus stori,demonstr,demonstr adag,escapad,escapad demonstr,gander,gander occasion,good,good gander,good goos,goos,goos good,occasion,occasion amus,seri,seri escapad,stori
0,0.158274,0.158274,0.266535,0.266535,0.158274,0.158274,0.158274,0.176241,0.266535,0.266535,0.267982,0.266535,0.158274,0.158274,0.266535,0.266535,0.266535,0.176241,0.226580,0.266535
1,0.282513,0.282513,0.000000,0.000000,0.282513,0.282513,0.282513,0.314583,0.000000,0.000000,0.282513,0.000000,0.282513,0.282513,0.000000,0.000000,0.000000,0.314583,0.404435,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000

In [113]:
r.join(df)

,Sentiment,adag,adag good,amus,amus stori,demonstr,demonstr adag,escapad,escapad demonstr,gander,...,good,good gander,good goos,goos,goos good,occasion,occasion amus,seri,seri escapad,stori
0,1,0.158274,0.158274,0.266535,0.266535,0.158274,0.158274,0.158274,0.176241,0.266535,...,0.267982,0.266535,0.158274,0.158274,0.266535,0.266535,0.266535,0.176241,0.226580,0.266535
1,2,0.282513,0.282513,0.000000,0.000000,0.282513,0.282513,0.282513,0.314583,0.000000,...,0.282513,0.000000,0.282513,0.282513,0.000000,0.000000,0.000000,0.314583,0.404435,0.000000
2,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
3,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
5,2,0.328977,0.328977,0.000000,0.000000,0.328977,0.328977,0.328977,0.366321,0.000000,...,0.328977,0.000000,0.328977,0.328977,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,2,0.328977,0.328977,0.000000,0.000000,0.328977,0.328977,0.328977,0.366321,0.000000,...,0.328977,0.000000,0.328977,0.328977,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2,0.377964,0.377964,0.000000,0.000000,0.377964,0.377964,0.000000,0.000000,0.000000,...,0.377964,0.000000,0.377964,0.377964,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000